// Prompt tile pools for MINEFIELD — DEFAULTS (immutable bake-in)
// Live pool lives at window.MINEFIELD_PROMPTS and is set by armory.jsx
window.MINEFIELD_DEFAULT_PROMPTS = {
 drink: [
  { title: "BOTTOMS UP",         body: "Take 3 sips and top yourself up." },
  { title: "ALL FOR ONE",        body: "...and one for all. Everyone takes 3 sips." },
  { title: "EVERYONE HATES YOU", body: "Everyone takes 2 sips alongside yours." },
  { title: "THE CHOSEN ONE",     body: "Everyone takes 3 sips. Except you." },
  { title: "TO THE LEFT",        body: "Everyone passes their drink to the person on their left." },
  { title: "IS THAT A GAP?",     body: "Everyone pours a small top-up into your glass." },
  { title: "CONGRATULATIONS",    body: "Pick everyone's next drink. No arguments." },
  { title: "KA-CHING",           body: "The person who drew the previous card buys your next drink." },
  { title: "THAT'S MATES",       body: "Person to your right buys your next drink." },
  { title: "MIRROR IMAGE",       body: "Pick a player. Match every sip they take until your next turn." },
  { title: "UPGRADE",            body: "Whatever you're drinking, upgrade it. No downgrades." },
  { title: "THE CHASER",         body: "Take a sip of something different after your next drink." },
  { title: "CROWDFUNDED",        body: "Everyone chips in toward your next drink." },
  { title: "DOUBLE TROUBLE",     body: "You and the person opposite must drink in sync until your next turn." },
  { title: "OPEN TAB",           body: "You decide what everyone's next drink is. Use this wisely." },
],

dare: [
  { title: "SUCK IT UP",         body: "You must drink through a straw for the next 3 rounds." },
  { title: "JET LAGGED",         body: "Have a coffee alongside your next drink." },
  { title: "MOO-VE ON",          body: "Take a few sips of milk. Yes, really." },
  { title: "BOMB JAGER",         body: "Do a Jager Bomb — in reverse. Jager first, then the mixer." },
  { title: "GRAND NATIONAL",     body: "Slap your own backside every time you take a sip. No exceptions." },
  { title: "PAPARAZZI",          body: "Anyone you sneakily photograph in the next 10 minutes takes 2 sips." },
  { title: "NO HANDS",           body: "Drink your next drink without using your hands. Any method." },
  { title: "KNEEL BEFORE",       body: "Take your next drink on one knee." },
  { title: "ACCENT ON",          body: "Adopt an accent now. Hold it until your next turn or take 2 sips." },
  { title: "HOT MIC",            body: "Narrate everything you do out loud for the next 3 minutes." },
  { title: "THE MANNEQUIN",      body: "Anyone can shout FREEZE once this round. Last to stop moving takes 2 sips." },
  { title: "SPEECH!",            body: "30 seconds, say something nice about the person to your right. Rated under 6/10? Take 2 sips." },
  { title: "IMPRESSION",         body: "Impersonate someone in the group. They guess who. Wrong? Take 2 sips." },
  { title: "ROAST",              body: "One roast each from the group. You cannot react." },
  { title: "THE SOMMELIER",      body: "Pour yourself something you haven't had tonight." },
  { title: "MOCKTAIL",           body: "Your next drink must be non-alcoholic. Your choice, your dignity." },
  { title: "SALUTE",             body: "Salute before every sip until the next card is drawn." },
  { title: "PINKY UP",           body: "Pinky extended on every drink for the rest of the night. Caught without it? Take 2 sips." },
  { title: "THE ROYALE",         body: "Bow or curtsy to whoever hands you a drink for the next round." },
  { title: "SILENCE",            body: "No speaking until your next turn. Gestures only. Slip up? Take 2 sips." },
  { title: "PARANOIA",           body: "Whisper a question to the person on your right. They say the answer out loud — not the question. Group guesses it." },
  { title: "CONFESSIONAL",       body: "Tell the table something nobody here knows about you. Skip? Take 2 sips." },
  { title: "EXPOSURE",           body: "Show the group your most recent photo, text, and search history. Take a sip for each one you skip." },
],

hotseat: [
  { title: "HAPPY BIRTHDAY",     body: "It's your 18th again. Pick 2 people to celebrate with — all three of you take 2 sips." },
  { title: "HOT SEAT",           body: "Each player asks you one question. Answer honestly or take 2 sips." },
  { title: "MOST LIKELY",        body: "Group votes: who in this room is most likely to cause a scene tonight? Most votes takes 2 sips." },
  { title: "TRUTH TAX",          body: "Answer honestly: what's the worst thing you've done this week? Or take 2 sips." },
  { title: "RANK THE ROOM",      body: "Rank everyone here by who you'd trust with your phone unlocked. Lowest-ranked takes 2 sips." },
  { title: "ONE WORD",           body: "Group describes you in one word each. Take a sip for any you disagree with." },
  { title: "WORST DATE",         body: "Tell the group about your worst date. Spare no detail." },
  { title: "GUILTY OR NOT",      body: "Read out 3 scenarios. Raise your hand if guilty. Most hands each round takes a sip." },
],

rule: [
  { title: "BUFFALO!",           body: "Opposite hand only for drinks from now on. Caught using the wrong one? Take 2 sips." },
  { title: "THUMBMASTER",        body: "Press your thumb to the table at any time. Last to copy you takes 2 sips. Lasts until next Rule tile." },
  { title: "MUMS THE WORD",      body: "Everyone refers to each other by their mum's name. Slip up? Take a sip." },
  { title: "SIPPY CUP",          body: "Two hands on every drink for the rest of the game. One hand? Take 2 sips." },
  { title: "RULE MAKER",         body: "Create any rule. It stands until someone lands on another Rule tile." },
  { title: "WRONG HAND",         body: "Switch to your non-dominant hand for drinks. Lasts until next Rule tile." },
  { title: "STAND & DRINK",      body: "You must stand up to take any sip for the rest of the game." },
  { title: "NO NAMES",           body: "No first names. Everyone picks a nickname right now. Slip up? Take 2 sips." },
  { title: "QUESTION MASTER",    body: "Until your next turn: anyone who answers a question you ask takes 2 sips." },
  { title: "SPEED LIMIT",        body: "Sips only — no gulping — until next Rule tile. Group polices it." },
  { title: "THE BARTENDER",      body: "You choose what everyone drinks next round. No input from them." },
  { title: "JAZZ HANDS",         body: "Jazz hands before picking up any drink. Forget? Take 2 sips." },
  { title: "REVERSE ROBIN",      body: "Person to your left buys your next drink." },
],

minigame: [
  { title: "FIVES",              body: "Everyone plays a round of fives. Loser takes 2 sips." },
  { title: "HEADS OR TAILS",     body: "Flip a coin. Call it wrong? Take 2 sips." },
  { title: "SHOT ROULETTE",      body: "Pour 6 small drinks — one is water. Everyone picks one and drinks simultaneously." },
  { title: "21",                 body: "Count to 21 around the circle, 1-2-or-3 numbers at a time. Say 21 = make a rule. Mess up = take 2 sips." },
  { title: "SPOOF",              body: "0-3 coins in fist. Closest guess to the total — without going over — buys the next round." },
  { title: "RPS TOURNAMENT",     body: "Rock Paper Scissors, everyone in. Winner assigns 3 sips however they like." },
  { title: "COIN STACK",         body: "Stack as many coins as you can one-handed on your elbow then catch them. Lowest count takes 2 sips." },
  { title: "CATEGORIES",         body: "Name a category. Go around. First to blank or repeat takes 2 sips." },
  { title: "WORD CHAIN",         body: "One word. Player to your left rhymes it. Keep going. First to break the chain takes 2 sips." },
  { title: "ALPHABET",           body: "Pick a topic. Name one thing per letter, A to Z. Skip or repeat? Take 2 sips." },
  { title: "PUB OLYMPICS",       body: "Name an event — furthest beer mat, steadiest hand, etc. Winner assigns 3 sips." },
],

safe: [
  { title: "IT'S HOT OUT",       body: "Treat yourself to a glass of water. Responsible." },
  { title: "ALL CLEAR",          body: "Nothing happens. Enjoy the peace." },
  { title: "MEDIC",              body: "Pass your drink to anyone. They take a sip for you." },
  { title: "SHIELD",             body: "Bank this. Cancel any one tile before it triggers. One use only." },
  { title: "SLOW LANE",          body: "Skip your next tile penalty, whatever it is." },
],
};
